<?php
/**
 * @file
 * cod_sponsor_sales.module
 *
 * Main entry for the cod_sponsor_sales feature.
 */

include_once 'includes/SponsorSales.inc';
include_once 'includes/EntityForm.inc';
include_once 'includes/SponsorSalesForm.inc';

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cod_sponsor_sales_form_sponsor_node_form_alter(&$form, &$form_state) {
  $sponsor_sales_form = new SponsorSalesForm($form);

  if ($sponsor_sales_form->isReady()) {
    $sponsor_sales_form->addDynamicSponsorshipItem();
    $sponsor_sales_form->addCheckoutRedirect();
  }

}
