<?php
/**
 * @file
 * Code for the front splash area, I want this in a tpl to make it easily
 * updateable by code.
 */

/**
 * Implements hook_block_info().
 */
function drupaldelphia_splash_block_info() {
  $blocks = array();
  $blocks['splash'] = array(
    'info' => t('Splash Block'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupaldelphia_splash_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'splash':
      $block['subject'] = '';
      $block['content'] = theme('splash');
      break;
  }
  return $block;
}
/**
 * Implements hook_theme().
 */
function drupaldelphia_splash_theme($existing, $type, $theme, $path) {
  return array(
    'splash' => array(
      'template' => 'splash',
      'path'     => drupal_get_path('module', 'drupaldelphia_splash') . '/theme',
    ),
  );
}
